/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ScoresPage;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import my.OptionsPage.OptionsPage;

/**
 *
 * @author Alaa
 */
public class scoresPage extends javax.swing.JFrame {

    /**
     * Creates new form scoresPage
     */
  //  ArrayList<String> Single = new ArrayList<String>();
   // ArrayList<String> Multi = new ArrayList<String>();
    
   public ArrayList<String> arr = Scores.GetSingle();
   public ArrayList<String> multi = Scores.GetMulti();
    ArrayList<Gamer> Gamers = new ArrayList<Gamer>();
    public scoresPage() {
        initComponents();
        
        this.setSize(1000,750);
        this.setLocationRelativeTo(null);
        jTextArea1.setText("");
        // singleRadioButton.setActionCommand("Single");
       //  MultiRadioButton.setActionCommand("Multi");
       // Single = Scores.GetSingle();
      //  Multi = Scores.GetMulti();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModeBG = new javax.swing.ButtonGroup();
        BackBTN = new javax.swing.JButton();
        ScoreLabel = new javax.swing.JLabel();
        BestScoreLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BestPlayerName = new javax.swing.JLabel();
        singleRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        MultiRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/ScoresPage/Back button(medium).png"))); // NOI18N
        BackBTN.setBorderPainted(false);
        BackBTN.setContentAreaFilled(false);
        BackBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BackBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BackBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackBTNMouseMoved(evt);
            }
        });
        BackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackBTNMouseExited(evt);
            }
        });
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BackBTN);
        BackBTN.setBounds(0, 0, 110, 90);

        ScoreLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/ScoresPage/Scores.png"))); // NOI18N
        getContentPane().add(ScoreLabel);
        ScoreLabel.setBounds(390, 40, 210, 70);

        BestScoreLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/ScoresPage/Best score.png"))); // NOI18N
        getContentPane().add(BestScoreLabel);
        BestScoreLabel.setBounds(150, 140, 280, 100);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Unicode MS", 2, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setSelectionColor(new java.awt.Color(222, 157, 87));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 230, 410, 360);

        BestPlayerName.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        BestPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(BestPlayerName);
        BestPlayerName.setBounds(450, 160, 390, 50);

        ModeBG.add(singleRadioButton);
        singleRadioButton.setContentAreaFilled(false);
        singleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(singleRadioButton);
        singleRadioButton.setBounds(670, 320, 30, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/ScoresPage/Single.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 300, 160, 80);

        ModeBG.add(MultiRadioButton);
        MultiRadioButton.setContentAreaFilled(false);
        MultiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MultiRadioButton);
        MultiRadioButton.setBounds(670, 440, 30, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/ScoresPage/Multi.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(700, 420, 160, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/ScoresPage/Options Page.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        new OptionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void BackBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBTNMouseMoved
        BackBTN.setIcon(new ImageIcon(getClass().getResource("/my/ScoresPage/Back button.png")));
    }//GEN-LAST:event_BackBTNMouseMoved

    private void BackBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBTNMouseExited
        BackBTN.setIcon(new ImageIcon(getClass().getResource("/my/ScoresPage/Back button(medium).png")));
    }//GEN-LAST:event_BackBTNMouseExited

    private void singleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleRadioButtonActionPerformed
//        ArrayList<Gamer> Single_Gamers = new ArrayList<Gamer>();
//            Single_Gamers.clear();
//            String []split = null; 
//        jTextArea1.setText("");
//          for (String single : Single )
//            {
//                split = single.split("#");
//                Single_Gamers.add(new Gamer(split[0],Integer.valueOf(split[1])));
//            }
//            Collections.sort(Single_Gamers,Collections.reverseOrder());
//            
//            BestPlayerName.setText(Single_Gamers.get(0).name +"  "+ Single_Gamers.get(0).Score);
//             for (String single :Scores.GetMulti())
//            {
//                split = single.split("#");
//                Single_Gamers.add(new Gamer(split[0],Integer.valueOf(split[1])));
//            }
//            for (int i = 0; i < Single_Gamers.size();i++)
//                    jTextArea1.append(Single_Gamers.get(i).name + "  " +Single_Gamers.get(i).Score + "\n");
//     
         
        
       String [] split;

        Gamers.clear();
        jTextArea1.setText(null);
            
            for(int i = 0; i < arr.size(); i++)
            System.out.println(arr.get(i));
            
            for(int i = 0; i < arr.size(); i++)
            {
                split = arr.get(i).split("#");
                Gamers.add(new Gamer(split[0],Integer.valueOf(split[1])));
            }
            
            Collections.sort(Gamers,Collections.reverseOrder());
            
            BestPlayerName.setText(Gamers.get(0).name +"  "+ Gamers.get(0).Score);
            
            for (int i = 0; i < Gamers.size();i++)
                   jTextArea1.append(Gamers.get(i).name + "  " +Gamers.get(i).Score + "\n");
         
        
        
    }//GEN-LAST:event_singleRadioButtonActionPerformed

    private void MultiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiRadioButtonActionPerformed
        // TODO add your handling code here:
//      ArrayList<Gamer> Multi_Gamers = new ArrayList<Gamer>();
//            Multi_Gamers.clear();
//            String []split = null; 
//        jTextArea1.setText("");
//            for (String single :Multi)
//            {
//                split = single.split("#");
//                Multi_Gamers.add(new Gamer(split[0],Integer.valueOf(split[1])));
//            }
//            Collections.sort(Multi_Gamers,Collections.reverseOrder());
//            
//            BestPlayerName.setText(Multi_Gamers.get(0).name +"  "+ Multi_Gamers.get(0).Score);
//            for (Gamer split1 : Multi_Gamers) {
//                System.out.println(split1.name);
//            
//        }
//            
//            for (int i = 0; i < Multi_Gamers.size();i++)
//                    jTextArea1.append(Multi_Gamers.get(i).name + "  " +Multi_Gamers.get(i).Score + "\n");
//      
        String [] split;

        Gamers.clear();
        jTextArea1.setText(null);
            
            for(int i = 0; i < multi.size(); i++)
            System.out.println(multi.get(i));
            
            for(int i = 0; i < multi.size(); i++)
            {
                split = multi.get(i).split("#");
                Gamers.add(new Gamer(split[0],Integer.valueOf(split[1])/2));
            }

            Collections.sort(Gamers,Collections.reverseOrder());
            
            BestPlayerName.setText(Gamers.get(0).name +"  "+ Gamers.get(0).Score);
            
            for (int i = 0; i < Gamers.size();i++)
                   jTextArea1.append(Gamers.get(i).name + "  " +Gamers.get(i).Score + "\n");
        
        
        
    }//GEN-LAST:event_MultiRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoresPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoresPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoresPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoresPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scoresPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BestPlayerName;
    private javax.swing.JLabel BestScoreLabel;
    private javax.swing.ButtonGroup ModeBG;
    private javax.swing.JRadioButton MultiRadioButton;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton singleRadioButton;
    // End of variables declaration//GEN-END:variables


    
    
    
  }
