/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.CongratulationsPage;

import javax.swing.ImageIcon;
import my.StartPage.StartPage;
import GameGui.*;
import javafx.scene.media.AudioClip;
import javax.swing.JLabel;
import my.SingleModePage.SingleMode;

import my.TwoPlayersModePage.TwoPlayersMode;
/**
 *
 * @author Alaa
 */
public class Congratulating extends javax.swing.JFrame {
   public static AudioClip audio;
   static  String   Name;
   static String Score;
    boolean Single = SingleMode.singleMode;
    boolean multi = TwoPlayersMode.twoPlayersMode;
    /**
     * Creates new form Congratulating
     */
 
    public Congratulating(String name,String score) {
        initComponents();
        Name = name;
        Score = score;
        NameL.setText(Name);
        ScoreL.setText(Score);
        this.setLocationRelativeTo(null);
         audio = new AudioClip(this.getClass().getResource("congratulation.wav").toString());
                 audio.play();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WinnerLabel = new javax.swing.JLabel();
        CongratulationsLabel = new javax.swing.JLabel();
        ScoreLabel = new javax.swing.JLabel();
        PlayAgainBTN = new javax.swing.JButton();
        ReturnBTN = new javax.swing.JButton();
        QuitBTN = new javax.swing.JButton();
        NameL = new javax.swing.JLabel();
        ScoreL = new javax.swing.JLabel();
        PageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setLocation(new java.awt.Point(350, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 340));
        setSize(new java.awt.Dimension(608, 336));
        getContentPane().setLayout(null);

        WinnerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/CongratulationsPage/Winner Label.png"))); // NOI18N
        getContentPane().add(WinnerLabel);
        WinnerLabel.setBounds(180, 0, 230, 70);

        CongratulationsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/CongratulationsPage/Congratulations Label.png"))); // NOI18N
        getContentPane().add(CongratulationsLabel);
        CongratulationsLabel.setBounds(100, 50, 440, 80);

        ScoreLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/CongratulationsPage/Score.png"))); // NOI18N
        getContentPane().add(ScoreLabel);
        ScoreLabel.setBounds(20, 200, 150, 50);

        PlayAgainBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/CongratulationsPage/Play Again.png"))); // NOI18N
        PlayAgainBTN.setBorderPainted(false);
        PlayAgainBTN.setContentAreaFilled(false);
        PlayAgainBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PlayAgainBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PlayAgainBTNMouseMoved(evt);
            }
        });
        PlayAgainBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayAgainBTNMouseExited(evt);
            }
        });
        PlayAgainBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayAgainBTNActionPerformed(evt);
            }
        });
        getContentPane().add(PlayAgainBTN);
        PlayAgainBTN.setBounds(120, 260, 105, 80);

        ReturnBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/CongratulationsPage/Return to menu.png"))); // NOI18N
        ReturnBTN.setBorderPainted(false);
        ReturnBTN.setContentAreaFilled(false);
        ReturnBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ReturnBTNMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ReturnBTNMouseMoved(evt);
            }
        });
        ReturnBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReturnBTNMouseExited(evt);
            }
        });
        ReturnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnBTN);
        ReturnBTN.setBounds(250, 270, 99, 60);

        QuitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/CongratulationsPage/Quit.png"))); // NOI18N
        QuitBTN.setBorderPainted(false);
        QuitBTN.setContentAreaFilled(false);
        QuitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuitBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                QuitBTNMouseMoved(evt);
            }
        });
        QuitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuitBTNMouseExited(evt);
            }
        });
        QuitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(QuitBTN);
        QuitBTN.setBounds(380, 260, 99, 80);

        NameL.setBackground(new java.awt.Color(255, 255, 255));
        NameL.setFont(new java.awt.Font("Brush Script MT", 2, 48)); // NOI18N
        NameL.setForeground(new java.awt.Color(255, 255, 255));
        NameL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NameL);
        NameL.setBounds(160, 140, 270, 40);

        ScoreL.setFont(new java.awt.Font("Brush Script MT", 2, 48)); // NOI18N
        ScoreL.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ScoreL);
        ScoreL.setBounds(200, 210, 190, 30);

        PageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/CongratulationsPage/firework.gif"))); // NOI18N
        PageBackground.setPreferredSize(new java.awt.Dimension(636, 336));
        getContentPane().add(PageBackground);
        PageBackground.setBounds(0, 0, 600, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayAgainBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayAgainBTNActionPerformed
        // TODO add your handling code here:
        audio.stop();
        if(Single){
            SingleMode single = new SingleMode();
            single.setVisible(true);
        }
        else if(multi){
            TwoPlayersMode two = new TwoPlayersMode();
            two.setVisible(true);
        }
        
    }//GEN-LAST:event_PlayAgainBTNActionPerformed

    private void ReturnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBTNActionPerformed
        audio.stop();
        new StartPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnBTNActionPerformed

    private void PlayAgainBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayAgainBTNMouseMoved
        PlayAgainBTN.setIcon(new ImageIcon(getClass().getResource("/my/CongratulationsPage/Play Again(small).png")));
    }//GEN-LAST:event_PlayAgainBTNMouseMoved

    private void PlayAgainBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayAgainBTNMouseExited
        PlayAgainBTN.setIcon(new ImageIcon(getClass().getResource("/my/CongratulationsPage/Play Again.png")));
    }//GEN-LAST:event_PlayAgainBTNMouseExited

    private void ReturnBTNMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBTNMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnBTNMouseDragged

    private void ReturnBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBTNMouseMoved
        ReturnBTN.setIcon(new ImageIcon(getClass().getResource("/my/CongratulationsPage/Return to menu(small).png")));
    }//GEN-LAST:event_ReturnBTNMouseMoved

    private void ReturnBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBTNMouseExited
        ReturnBTN.setIcon(new ImageIcon(getClass().getResource("/my/CongratulationsPage/Return to menu.png")));
    }//GEN-LAST:event_ReturnBTNMouseExited

    private void QuitBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitBTNMouseMoved
        QuitBTN.setIcon(new ImageIcon(getClass().getResource("/my/CongratulationsPage/Quit(small).png")));
    }//GEN-LAST:event_QuitBTNMouseMoved

    private void QuitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitBTNMouseExited
        QuitBTN.setIcon(new ImageIcon(getClass().getResource("/my/CongratulationsPage/Quit.png")));
    }//GEN-LAST:event_QuitBTNMouseExited

    private void QuitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_QuitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Congratulating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Congratulating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Congratulating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Congratulating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Congratulating(Name,Score).setVisible(true);
               //  audio = new AudioClip(this.getClass().getResource("congratulation.wav").toString());
                 //audio.play();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CongratulationsLabel;
    private javax.swing.JLabel NameL;
    private javax.swing.JLabel PageBackground;
    private javax.swing.JButton PlayAgainBTN;
    private javax.swing.JButton QuitBTN;
    private javax.swing.JButton ReturnBTN;
    private javax.swing.JLabel ScoreL;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JLabel WinnerLabel;
    // End of variables declaration//GEN-END:variables
}
