/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.StartPage;

import java.awt.Toolkit;
import javafx.scene.media.AudioClip;
import javax.swing.ImageIcon;
import my.OptionsPage.OptionsPage;
import my.SingleModePage.SingleMode;
import my.TwoPlayersModePage.TwoPlayersMode;


/**
 *
 * @author Alaa
 */


public class StartPage extends javax.swing.JFrame {
    /**
     * Creates new form StartPage
     */  
       public static AudioClip audio;
       public static TwoPlayersMode twoplayers;
    public StartPage() {
     
       this.setUndecorated(true); //removes the title bar
        this.setAlwaysOnTop(true); //this interface is always on top
        this.setResizable(false);
        
        this.setVisible(true);
        
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize(1000,750);
        this.setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SinglePlayerBTN = new javax.swing.JButton();
        TwoPlayersBTN = new javax.swing.JButton();
        OptionsBTN = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        Start = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        SinglePlayerBTN.setBackground(new java.awt.Color(255, 153, 153));
        SinglePlayerBTN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SinglePlayerBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/StartPage/Single Player button.png"))); // NOI18N
        SinglePlayerBTN.setBorder(null);
        SinglePlayerBTN.setBorderPainted(false);
        SinglePlayerBTN.setContentAreaFilled(false);
        SinglePlayerBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SinglePlayerBTN.setFocusPainted(false);
        SinglePlayerBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SinglePlayerBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SinglePlayerBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SinglePlayerBTN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SinglePlayerBTNStateChanged(evt);
            }
        });
        SinglePlayerBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SinglePlayerBTNMouseMoved(evt);
            }
        });
        SinglePlayerBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SinglePlayerBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SinglePlayerBTNMouseExited(evt);
            }
        });
        SinglePlayerBTN.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                SinglePlayerBTNComponentResized(evt);
            }
        });
        SinglePlayerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinglePlayerBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SinglePlayerBTN);
        SinglePlayerBTN.setBounds(260, 190, 440, 140);

        TwoPlayersBTN.setBackground(new java.awt.Color(255, 153, 153));
        TwoPlayersBTN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TwoPlayersBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/StartPage/Two Players button.png"))); // NOI18N
        TwoPlayersBTN.setBorder(null);
        TwoPlayersBTN.setBorderPainted(false);
        TwoPlayersBTN.setContentAreaFilled(false);
        TwoPlayersBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TwoPlayersBTN.setFocusPainted(false);
        TwoPlayersBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TwoPlayersBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        TwoPlayersBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TwoPlayersBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TwoPlayersBTNMouseMoved(evt);
            }
        });
        TwoPlayersBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TwoPlayersBTNMouseExited(evt);
            }
        });
        TwoPlayersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoPlayersBTNActionPerformed(evt);
            }
        });
        getContentPane().add(TwoPlayersBTN);
        TwoPlayersBTN.setBounds(280, 330, 410, 120);

        OptionsBTN.setBackground(new java.awt.Color(255, 153, 153));
        OptionsBTN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        OptionsBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/StartPage/Options button.png"))); // NOI18N
        OptionsBTN.setBorder(null);
        OptionsBTN.setBorderPainted(false);
        OptionsBTN.setContentAreaFilled(false);
        OptionsBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionsBTN.setFocusPainted(false);
        OptionsBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OptionsBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        OptionsBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OptionsBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                OptionsBTNMouseMoved(evt);
            }
        });
        OptionsBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionsBTNMouseExited(evt);
            }
        });
        OptionsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(OptionsBTN);
        OptionsBTN.setBounds(320, 440, 310, 126);

        ExitBTN.setBackground(new java.awt.Color(255, 153, 153));
        ExitBTN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ExitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/StartPage/Exit button.png"))); // NOI18N
        ExitBTN.setBorder(null);
        ExitBTN.setBorderPainted(false);
        ExitBTN.setContentAreaFilled(false);
        ExitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBTN.setFocusPainted(false);
        ExitBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ExitBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ExitBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ExitBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ExitBTNMouseMoved(evt);
            }
        });
        ExitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBTNMouseExited(evt);
            }
        });
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBTN);
        ExitBTN.setBounds(340, 570, 270, 110);

        Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/StartPage/Start page image.jpg"))); // NOI18N
        getContentPane().add(Start);
        Start.setBounds(0, -20, 1900, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TwoPlayersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoPlayersBTNActionPerformed
       twoplayers = new TwoPlayersMode();
      twoplayers.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TwoPlayersBTNActionPerformed

    private void SinglePlayerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinglePlayerBTNActionPerformed
        // TODO add your handling code here:
        new SingleMode().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SinglePlayerBTNActionPerformed

    private void SinglePlayerBTNComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SinglePlayerBTNComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_SinglePlayerBTNComponentResized

    private void SinglePlayerBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SinglePlayerBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SinglePlayerBTNMouseEntered

    private void SinglePlayerBTNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SinglePlayerBTNStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SinglePlayerBTNStateChanged

    private void SinglePlayerBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SinglePlayerBTNMouseMoved
        SinglePlayerBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Single Player button (medium).png")));  
    }//GEN-LAST:event_SinglePlayerBTNMouseMoved

    private void SinglePlayerBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SinglePlayerBTNMouseExited
        SinglePlayerBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Single Player button.png")));
    }//GEN-LAST:event_SinglePlayerBTNMouseExited

    private void TwoPlayersBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoPlayersBTNMouseMoved
        TwoPlayersBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Two Players button (medium).png")));
    }//GEN-LAST:event_TwoPlayersBTNMouseMoved

    private void TwoPlayersBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoPlayersBTNMouseExited
        TwoPlayersBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Two Players button.png")));
    }//GEN-LAST:event_TwoPlayersBTNMouseExited

    private void OptionsBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsBTNMouseMoved
         OptionsBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Options button (medium).png")));
    }//GEN-LAST:event_OptionsBTNMouseMoved

    private void OptionsBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsBTNMouseExited
        OptionsBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Options button.png")));
    }//GEN-LAST:event_OptionsBTNMouseExited

    private void ExitBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseMoved
       ExitBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Exit button (medium).png")));
    }//GEN-LAST:event_ExitBTNMouseMoved

    private void ExitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseExited
       ExitBTN.setIcon(new ImageIcon(getClass().getResource("/my/StartPage/Exit button.png")));
    }//GEN-LAST:event_ExitBTNMouseExited

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBTNActionPerformed

    private void OptionsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsBTNActionPerformed
        new OptionsPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OptionsBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
                audio = new AudioClip(this.getClass().getResource("Main music.wav").toString());
                audio.play();
            
        
        }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton OptionsBTN;
    private javax.swing.JButton SinglePlayerBTN;
    private javax.swing.JLabel Start;
    private javax.swing.JButton TwoPlayersBTN;
    // End of variables declaration//GEN-END:variables
}
