/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.PausePage;
import GameGui.DrawBoard;
import my.LevelsPage.Level;
import my.SingleModePage.SingleMode;
import my.StartPage.StartPage;
import my.TwoPlayersModePage.TwoPlayersMode;

/**
 *
 * @author Alaa
 */
public class Pause extends javax.swing.JFrame {

    /**
     * Creates new form Pause
     */
    public Pause() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PauseLabel = new javax.swing.JLabel();
        ReplayBTN = new javax.swing.JButton();
        ResumeBTN = new javax.swing.JButton();
        MainMenuBTN = new javax.swing.JButton();
        ResumeLabel = new javax.swing.JLabel();
        ReplayLabel = new javax.swing.JLabel();
        MenuLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 320));
        getContentPane().setLayout(null);

        PauseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/Pause.png"))); // NOI18N
        getContentPane().add(PauseLabel);
        PauseLabel.setBounds(180, 30, 160, 70);

        ReplayBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/replay btn.png"))); // NOI18N
        ReplayBTN.setBorderPainted(false);
        ReplayBTN.setContentAreaFilled(false);
        ReplayBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReplayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ReplayBTN);
        ReplayBTN.setBounds(190, 120, 160, 70);

        ResumeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/play.png"))); // NOI18N
        ResumeBTN.setBorderPainted(false);
        ResumeBTN.setContentAreaFilled(false);
        ResumeBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResumeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ResumeBTN);
        ResumeBTN.setBounds(40, 120, 97, 73);

        MainMenuBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/Home.png"))); // NOI18N
        MainMenuBTN.setBorderPainted(false);
        MainMenuBTN.setContentAreaFilled(false);
        MainMenuBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuBTNActionPerformed(evt);
            }
        });
        getContentPane().add(MainMenuBTN);
        MainMenuBTN.setBounds(400, 120, 97, 70);

        ResumeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/Resume.png"))); // NOI18N
        getContentPane().add(ResumeLabel);
        ResumeLabel.setBounds(0, 200, 170, 50);

        ReplayLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/Replay.png"))); // NOI18N
        getContentPane().add(ReplayLabel);
        ReplayLabel.setBounds(180, 200, 190, 60);

        MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/Main menu.png"))); // NOI18N
        getContentPane().add(MenuLabel);
        MenuLabel.setBounds(340, 200, 220, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/PausePage/Wooden board.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 556, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuBTNActionPerformed
     
        if (DrawBoard.Single && !DrawBoard.Player_single.winner &&!DrawBoard.single_computer.winner)
        {
            
            GameGui.ReturnGame.Save(DrawBoard.Name,"Computer",DrawBoard.Player_single.sqr_num,DrawBoard.single_computer.sqr_num);
        }
        else if (DrawBoard.multi && !DrawBoard.Player_single.winner &&!DrawBoard.Multi_player2.winner)
        {
              GameGui.ReturnGame.Save(DrawBoard.Name1,DrawBoard.Name2,DrawBoard.Player_single.sqr_num,DrawBoard.Multi_player2.sqr_num);
        }
        
        
       if(DrawBoard.Single){
       Level.Pass.setVisible(false);
      }
      else{
          TwoPlayersMode.Pass.setVisible(false);
      } 
       StartPage start = new StartPage();
       DrawBoard.initiatepage.setVisible(false);
       start.setVisible(true);
       DrawBoard.audio2.stop();
       //////////////////////////////////////////////////////////////////////////
       
       
       
       
       
       this.dispose();
       
    }//GEN-LAST:event_MainMenuBTNActionPerformed

    private void ResumeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeBTNActionPerformed
        // TODO add your handling code here:
       
        this.setVisible(false);
        
        this.dispose();
    }//GEN-LAST:event_ResumeBTNActionPerformed

    private void ReplayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplayBTNActionPerformed
        // TODO add your handling code here:
        if(DrawBoard.Single){
       //DrawBoard.fxPanel.removeAll();
       //DrawBoard.titleGroup.getChildren().clear();
       //DrawBoard.root.getChildren().clear();
       Level.Pass.setVisible(false);
      }
      else{
         //   DrawBoard.root.getChildren().clear();
           //DrawBoard.titleGroup.getChildren().clear();
          TwoPlayersMode.Pass.setVisible(false);
      } 
        SingleMode draw = new SingleMode();
        draw.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ReplayBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pause().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton MainMenuBTN;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JLabel PauseLabel;
    private javax.swing.JButton ReplayBTN;
    private javax.swing.JLabel ReplayLabel;
    private javax.swing.JButton ResumeBTN;
    private javax.swing.JLabel ResumeLabel;
    // End of variables declaration//GEN-END:variables
}
