/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.InfoPage;

import javax.swing.ImageIcon;
import my.OptionsPage.OptionsPage;

/**
 *
 * @author Alaa
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    public Info() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        OkBTN = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        InfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/InfoPage/Game info.png"))); // NOI18N
        getContentPane().add(InfoLabel);
        InfoLabel.setBounds(350, 20, 290, 80);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Unicode MS", 2, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("This game is developed by \"The Dark Knights\", a team of second year students at Faculty of Computer and Information Science in Ain Shams University, as an Object Oriented Programming project.\n\nDevelopers:\n- Abulrahman El Sayed Saeed.\n- Mohammed Soliman.\n- Esraa Saeed Awad.\n- Abeer Fathy.\n- Alaa Mohammed Mostafa.\n\n\"We hope you enjoy our version of this famous game.\n Thank you.\" \n                                                       -  The Dark Knights.\n\nSnake and Ladder, developed in 2019.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 120, 710, 330);

        OkBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/InfoPage/Ok button.png"))); // NOI18N
        OkBTN.setBorderPainted(false);
        OkBTN.setContentAreaFilled(false);
        OkBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OkBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OkBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        OkBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OkBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                OkBTNMouseMoved(evt);
            }
        });
        OkBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OkBTNMouseExited(evt);
            }
        });
        OkBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBTNActionPerformed(evt);
            }
        });
        getContentPane().add(OkBTN);
        OkBTN.setBounds(420, 640, 129, 90);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/InfoPage/Background.gif"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkBTNMouseMoved
        OkBTN.setIcon(new ImageIcon(getClass().getResource("/my/RulesPage/Ok button(small).png")));
    }//GEN-LAST:event_OkBTNMouseMoved

    private void OkBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkBTNMouseExited
        OkBTN.setIcon(new ImageIcon(getClass().getResource("/my/RulesPage/Ok button.png")));
    }//GEN-LAST:event_OkBTNMouseExited

    private void OkBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBTNActionPerformed
        new OptionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OkBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JButton OkBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
