/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.OptionsPage;

/**
 *
 * @author Alaa
 */

import my.StartPage.StartPage;

import java.awt.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.*;
import my.InfoPage.Info;
import my.RulesPage.Rules;
import my.ScoresPage.scoresPage;

public class OptionsPage extends javax.swing.JFrame {

    /**
     * Creates new form OptionsPage
     */
    
    public boolean sound;  //sound case: true means on .. false means off
    
    /**
     *
     */
    private void Sound()
   {
        try{
                  FileReader reader = new FileReader("Game.txt");
                  String st;
            try (BufferedReader bf = new BufferedReader(reader)) {
                st=bf.readLine();
            }
            switch (st) {
                case "true":
                    sound = true;
                    SoundBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/On button.png")));
                    break;
                case "false":
                    sound = false;
                    SoundBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Off button.png")));
                    break;
            }         
              }
           catch(Exception ex){
               JOptionPane.showMessageDialog(null, ex);
           }
   }
    
    public OptionsPage() {
        this.setUndecorated(true); //removes the title bar
        this.setAlwaysOnTop(true); //this interface is always on top
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);   
        Sound();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionsLabel = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();
        SoundBTN = new javax.swing.JToggleButton();
        SoundLabel = new javax.swing.JLabel();
        RulesBTN = new javax.swing.JButton();
        InfoBTN = new javax.swing.JButton();
        ScoresBTN = new javax.swing.JButton();
        BackgroundPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        OptionsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/Options Label.png"))); // NOI18N
        getContentPane().add(OptionsLabel);
        OptionsLabel.setBounds(350, 60, 250, 90);

        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/Back button(medium).png"))); // NOI18N
        BackBTN.setBorderPainted(false);
        BackBTN.setContentAreaFilled(false);
        BackBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBTN.setFocusPainted(false);
        BackBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BackBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BackBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackBTNMouseMoved(evt);
            }
        });
        BackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackBTNMouseExited(evt);
            }
        });
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BackBTN);
        BackBTN.setBounds(-20, 0, 150, 90);

        SoundBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/On button.png"))); // NOI18N
        SoundBTN.setBorderPainted(false);
        SoundBTN.setContentAreaFilled(false);
        SoundBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SoundBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SoundBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SoundBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SoundBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoundBTNMouseClicked(evt);
            }
        });
        SoundBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SoundBTN);
        SoundBTN.setBounds(570, 150, 170, 70);

        SoundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/Sound.png"))); // NOI18N
        getContentPane().add(SoundLabel);
        SoundLabel.setBounds(200, 150, 250, 80);

        RulesBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/Rules button.png"))); // NOI18N
        RulesBTN.setToolTipText("");
        RulesBTN.setBorderPainted(false);
        RulesBTN.setContentAreaFilled(false);
        RulesBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RulesBTN.setFocusPainted(false);
        RulesBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RulesBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RulesBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RulesBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RulesBTNMouseMoved(evt);
            }
        });
        RulesBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RulesBTNMouseExited(evt);
            }
        });
        RulesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesBTNActionPerformed(evt);
            }
        });
        getContentPane().add(RulesBTN);
        RulesBTN.setBounds(340, 270, 290, 100);

        InfoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/Info button.png"))); // NOI18N
        InfoBTN.setBorderPainted(false);
        InfoBTN.setContentAreaFilled(false);
        InfoBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoBTN.setFocusPainted(false);
        InfoBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        InfoBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        InfoBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InfoBTNMouseMoved(evt);
            }
        });
        InfoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoBTNMouseExited(evt);
            }
        });
        InfoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBTNActionPerformed(evt);
            }
        });
        getContentPane().add(InfoBTN);
        InfoBTN.setBounds(380, 380, 210, 110);

        ScoresBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/Scores button(small).png"))); // NOI18N
        ScoresBTN.setBorderPainted(false);
        ScoresBTN.setContentAreaFilled(false);
        ScoresBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ScoresBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ScoresBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ScoresBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ScoresBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ScoresBTNMouseMoved(evt);
            }
        });
        ScoresBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScoresBTNMouseExited(evt);
            }
        });
        ScoresBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoresBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ScoresBTN);
        ScoresBTN.setBounds(400, 490, 190, 110);

        BackgroundPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/OptionsPage/Options Page.jpg"))); // NOI18N
        getContentPane().add(BackgroundPhoto);
        BackgroundPhoto.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBTNMouseEntered

    private void BackBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBTNMouseExited
        BackBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Back button(medium).png")));
    }//GEN-LAST:event_BackBTNMouseExited

    private void BackBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBTNMouseMoved
        BackBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Back button.png")));
    }//GEN-LAST:event_BackBTNMouseMoved

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        new StartPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void SoundBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundBTNActionPerformed
       if ((SoundBTN.isSelected() && sound == true) || (!SoundBTN.isSelected() && sound == true) )
      {
          SoundBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Off button.png")));
          sound = false;
            try{
                 FileWriter writer = new FileWriter("Game.txt");
                 PrintWriter pwriter = new PrintWriter(writer);
                 pwriter.println("false");
                 pwriter.close();
             }
             catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex);
               }
      }
      else if(SoundBTN.isSelected() && sound == false || (!SoundBTN.isSelected() && sound == false))
      {
          SoundBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/On button.png")));
          sound = true;
           try{
                 FileWriter writer = new FileWriter("Game.txt");
                 PrintWriter pwriter = new PrintWriter(writer);
                 pwriter.println("true");
                 pwriter.close();
             }
             catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex);
               }
      }
        
    }//GEN-LAST:event_SoundBTNActionPerformed

    private void SoundBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoundBTNMouseClicked
     
    }//GEN-LAST:event_SoundBTNMouseClicked

    private void RulesBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RulesBTNMouseMoved
         RulesBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Rules button(small).png")));
    }//GEN-LAST:event_RulesBTNMouseMoved

    private void RulesBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RulesBTNMouseExited
        RulesBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Rules button.png")));
    }//GEN-LAST:event_RulesBTNMouseExited

    private void InfoBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoBTNMouseMoved
        InfoBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Info button(small).png")));
    }//GEN-LAST:event_InfoBTNMouseMoved

    private void InfoBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoBTNMouseExited
        InfoBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Info button.png")));
    }//GEN-LAST:event_InfoBTNMouseExited

    private void RulesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesBTNActionPerformed
        new Rules().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RulesBTNActionPerformed

    private void InfoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBTNActionPerformed
       new Info().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_InfoBTNActionPerformed

    private void ScoresBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoresBTNMouseExited
        ScoresBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Scores button.png")));
    }//GEN-LAST:event_ScoresBTNMouseExited

    private void ScoresBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoresBTNMouseMoved
        ScoresBTN.setIcon(new ImageIcon(getClass().getResource("/my/OptionsPage/Scores button(small).png")));
    }//GEN-LAST:event_ScoresBTNMouseMoved

    private void ScoresBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoresBTNActionPerformed
        new scoresPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ScoresBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsPage().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JLabel BackgroundPhoto;
    private javax.swing.JButton InfoBTN;
    private javax.swing.JLabel OptionsLabel;
    private javax.swing.JButton RulesBTN;
    private javax.swing.JButton ScoresBTN;
    private javax.swing.JToggleButton SoundBTN;
    private javax.swing.JLabel SoundLabel;
    // End of variables declaration//GEN-END:variables
}
