/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.NewOrContinueForm;

import GameGui.DrawBoard;
import javax.swing.ImageIcon;
import my.SingleModePage.SingleMode;
import my.StartPage.StartPage;
import my.TwoPlayersModePage.TwoPlayersMode;

/**
 *
 * @author Alaa
 */
public class NewOrContinue extends javax.swing.JFrame {

    /**
     * Creates new form NewOrContinue
     */
    public  static boolean Resume = false; 
    public NewOrContinue() {
        initComponents();
        
        this.setAlwaysOnTop(true);
        
        this.setSize(508,219);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HelloLabel = new javax.swing.JLabel();
        continueBTN = new javax.swing.JButton();
        new_gameBTN = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(873, 654));
        setSize(new java.awt.Dimension(873, 654));
        getContentPane().setLayout(null);

        HelloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/NewOrContinueForm/Hello.png"))); // NOI18N
        getContentPane().add(HelloLabel);
        HelloLabel.setBounds(160, 30, 180, 60);

        continueBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/NewOrContinueForm/Continue last game button.png"))); // NOI18N
        continueBTN.setBorderPainted(false);
        continueBTN.setContentAreaFilled(false);
        continueBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        continueBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        continueBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        continueBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                continueBTNMouseMoved(evt);
            }
        });
        continueBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continueBTNMouseExited(evt);
            }
        });
        continueBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBTNActionPerformed(evt);
            }
        });
        getContentPane().add(continueBTN);
        continueBTN.setBounds(50, 70, 170, 161);

        new_gameBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/NewOrContinueForm/New game button.png"))); // NOI18N
        new_gameBTN.setBorderPainted(false);
        new_gameBTN.setContentAreaFilled(false);
        new_gameBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        new_gameBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        new_gameBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        new_gameBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        new_gameBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                new_gameBTNMouseMoved(evt);
            }
        });
        new_gameBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_gameBTNMouseExited(evt);
            }
        });
        new_gameBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_gameBTNActionPerformed(evt);
            }
        });
        getContentPane().add(new_gameBTN);
        new_gameBTN.setBounds(230, 120, 283, 90);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/NewOrContinueForm/Wooden board.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(-20, 0, 530, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBTNActionPerformed
        // TODO add your handling code here:
        Resume = true ;
        setVisible(false);
       if(SingleMode.singleMode)
            SingleMode.lev.dispose();
        else if (TwoPlayersMode.twoPlayersMode)
            StartPage.twoplayers.dispose();
        DrawBoard move = new DrawBoard();
        dispose();
    }//GEN-LAST:event_continueBTNActionPerformed

    private void continueBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBTNMouseMoved
        continueBTN.setIcon(new ImageIcon(getClass().getResource("/my/NewOrContinueForm/Continue last game button(small).png")));
    }//GEN-LAST:event_continueBTNMouseMoved

    private void continueBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBTNMouseExited
        continueBTN.setIcon(new ImageIcon(getClass().getResource("/my/NewOrContinueForm/Continue last game button.png")));
    }//GEN-LAST:event_continueBTNMouseExited

    private void new_gameBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_gameBTNMouseMoved
        new_gameBTN.setIcon(new ImageIcon(getClass().getResource("/my/NewOrContinueForm/New game button(small).png")));
    }//GEN-LAST:event_new_gameBTNMouseMoved

    private void new_gameBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_gameBTNMouseExited
        new_gameBTN.setIcon(new ImageIcon(getClass().getResource("/my/NewOrContinueForm/New game button.png")));
    }//GEN-LAST:event_new_gameBTNMouseExited

    private void new_gameBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_gameBTNActionPerformed
        // TODO add your handling code here:
        Resume = false ;
        setVisible(false);
        if(SingleMode.singleMode)
            SingleMode.lev.dispose();
        else if (TwoPlayersMode.twoPlayersMode)
            StartPage.twoplayers.dispose();
        DrawBoard move = new DrawBoard();
        dispose();
    }//GEN-LAST:event_new_gameBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrContinue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrContinue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrContinue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrContinue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOrContinue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JButton continueBTN;
    private javax.swing.JButton new_gameBTN;
    // End of variables declaration//GEN-END:variables
}
